import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { buildUserMessageContent } from "@/types/agent-types";
import { UserMessageBlock } from "./UserMessageBlock";

describe("UserMessageBlock", () => {
  it("uses provider-neutral copy for pending receipt state", () => {
    render(<UserMessageBlock content="steer now" deliveryState="pending_agent" />);

    expect(screen.getByText("Not received by agent yet…")).toBeInTheDocument();
    expect(screen.queryByText(/OpenCode/)).toBeNull();
  });

  it("visually distinguishes pending prompt delivery", () => {
    render(<UserMessageBlock content="steer now" deliveryState="pending_agent" />);

    const bubble = screen.getByTestId("user-message-bubble");
    expect(bubble).toHaveAttribute("data-prompt-delivery-state", "pending_agent");
    expect(bubble).toHaveClass("border-amber-500/50", "bg-amber-500/10");
    expect(screen.getByText("Not received by agent yet…")).toHaveClass("text-amber-300");
  });

  it("renders generated-by-session provenance for delegated prompts", () => {
    render(
      <UserMessageBlock
        content="please investigate"
        origin={{
          originKind: "session_generated",
          sourceSessionId: 123,
          sourceFeatureId: 45,
          sourceProjectId: 6,
          sourceMessageId: 789,
          note: "spawned helper",
          createdAt: "2026-06-18T12:00:00Z",
        }}
      />,
    );

    expect(screen.getByText("Generated by another session")).toBeInTheDocument();
    expect(screen.getByText("Session 123")).toBeInTheDocument();
  });

  it("renders non-image attachment filenames instead of image previews", () => {
    const content = buildUserMessageContent("review this", [
      {
        base64: "JVBERi0x",
        fileName: "requirements.pdf",
        kind: "document",
        mimeType: "application/pdf",
      },
    ]);

    render(<UserMessageBlock content={content} />);

    expect(screen.getByText("requirements.pdf")).toBeInTheDocument();
    expect(screen.queryByRole("img")).toBeNull();
  });
});
