import { PaperclipIcon } from "lucide-react";
import type { ReactElement, ReactNode } from "react";
import { Markdown } from "@/components/Markdown";
import { cn } from "@/lib/utils";
import { parseUserMessageContent, type ParsedPromptAttachment } from "@/types/agent-types";
import type { AgentMessageOrigin } from "@/api/generated";

interface UserMessageBlockProps {
  content: string;
  deliveryState?: "pending_agent";
  origin?: AgentMessageOrigin | null;
  /** On-hover action row (Copy / Fork / Rewind) rendered under the bubble. */
  actions?: ReactNode;
}

export function UserMessageBlock({
  content,
  deliveryState,
  origin,
  actions,
}: UserMessageBlockProps): ReactElement {
  const { text: textContent, images, attachments } = parseUserMessageContent(content);
  const isPendingDelivery = deliveryState === "pending_agent";
  const isGenerated = origin?.originKind === "session_generated";

  return (
    <div className="group/usermsg my-1 flex flex-col items-end">
      <div
        data-testid="user-message-bubble"
        data-prompt-delivery-state={deliveryState}
        className={cn(
          "max-w-[80%] rounded-md border px-3 py-1.5 text-sm",
          isPendingDelivery
            ? "border-amber-500/50 bg-amber-500/10"
            : "border-primary/30 bg-primary/10",
        )}
      >
        <Markdown content={textContent} className="user-message-markdown" />
        {images.length > 0 && (
          <div className="mt-2 flex flex-wrap gap-2">
            {images.map((img, i) => (
              <img
                key={i}
                src={`data:${img.mediaType};base64,${img.data}`}
                alt={`Attachment ${i + 1}`}
                className="max-h-48 max-w-full rounded border border-border"
              />
            ))}
          </div>
        )}
        {attachments.length > 0 && <AttachmentFileList attachments={attachments} />}
        {isGenerated && <GeneratedBySessionBadge origin={origin} />}
      </div>
      {isPendingDelivery && (
        <div className="mt-0.5 flex items-center gap-1.5 font-mono text-[10.5px]">
          <span
            className="size-1.5 animate-pulse rounded-full bg-amber-400/90"
            aria-hidden="true"
          />
          <span className="text-amber-300">Not received by agent yet…</span>
        </div>
      )}
      {actions}
    </div>
  );
}

function GeneratedBySessionBadge({ origin }: { origin: AgentMessageOrigin }): ReactElement {
  const sessionLabel = origin.sourceSessionId ? `Session ${origin.sourceSessionId}` : "a session";
  const tooltipParts = [
    origin.sourceProjectId ? `Project ${origin.sourceProjectId}` : null,
    origin.sourceFeatureId ? `Feature ${origin.sourceFeatureId}` : null,
    origin.sourceMessageId ? `Message ${origin.sourceMessageId}` : null,
    origin.note,
  ].filter((part): part is string => Boolean(part));

  return (
    <div
      className="mt-2 flex flex-wrap items-center justify-end gap-1.5 border-t border-primary/20 pt-1.5 font-mono text-[10.5px] text-muted-foreground"
      title={tooltipParts.join(" · ") || undefined}
    >
      <span className="rounded-full border border-primary/30 bg-background/50 px-1.5 py-0.5">
        Generated by another session
      </span>
      <span className="text-foreground/70">{sessionLabel}</span>
    </div>
  );
}

function AttachmentFileList({
  attachments,
}: {
  attachments: ParsedPromptAttachment[];
}): ReactElement {
  return (
    <div className="mt-2 flex flex-wrap gap-2">
      {attachments.map((attachment, index) => (
        <span
          key={`${attachment.fileName}:${attachment.mimeType}:${index}`}
          className="inline-flex max-w-full items-center gap-1.5 rounded-md border border-border bg-background/70 px-2 py-1 font-mono text-[11.5px] text-muted-foreground"
        >
          <PaperclipIcon className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
          <span className="truncate">{attachment.fileName}</span>
        </span>
      ))}
    </div>
  );
}
