import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  site: "https://cadencr.com",
  base: "/",
  trailingSlash: "ignore",
  // Preserve Astro 6 whitespace behavior while moving to Astro 7's stricter
  // compiler. The new `"jsx"` default can remove meaningful spacing between
  // adjacent inline elements.
  compressHTML: true,
  integrations: [
    mdx({ gfm: true }),
    sitemap({
      // 404 is auto-generated by Astro and must never be indexed.
      filter: (page) => !page.endsWith("/404/") && !page.endsWith("/404"),
      changefreq: "weekly",
      priority: 0.7,
      lastmod: new Date(),
    }),
  ],
  vite: { plugins: [tailwindcss()] },
  build: { format: "directory" },
});
