/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WsSessionSessionIdRouteImport } from './routes/ws-session.$sessionId'
import { Route as ProjectsProjectIdFeaturesFeatureIdRouteImport } from './routes/projects/$projectId/features/$featureId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WsSessionSessionIdRoute = WsSessionSessionIdRouteImport.update({
  id: '/ws-session/$sessionId',
  path: '/ws-session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdFeaturesFeatureIdRoute =
  ProjectsProjectIdFeaturesFeatureIdRouteImport.update({
    id: '/projects/$projectId/features/$featureId',
    path: '/projects/$projectId/features/$featureId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/ws-session/$sessionId': typeof WsSessionSessionIdRoute
  '/projects/$projectId/features/$featureId': typeof ProjectsProjectIdFeaturesFeatureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/ws-session/$sessionId': typeof WsSessionSessionIdRoute
  '/projects/$projectId/features/$featureId': typeof ProjectsProjectIdFeaturesFeatureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/schedules': typeof SchedulesRoute
  '/settings': typeof SettingsRoute
  '/ws-session/$sessionId': typeof WsSessionSessionIdRoute
  '/projects/$projectId/features/$featureId': typeof ProjectsProjectIdFeaturesFeatureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/schedules'
    | '/settings'
    | '/ws-session/$sessionId'
    | '/projects/$projectId/features/$featureId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/schedules'
    | '/settings'
    | '/ws-session/$sessionId'
    | '/projects/$projectId/features/$featureId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/schedules'
    | '/settings'
    | '/ws-session/$sessionId'
    | '/projects/$projectId/features/$featureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  SchedulesRoute: typeof SchedulesRoute
  SettingsRoute: typeof SettingsRoute
  WsSessionSessionIdRoute: typeof WsSessionSessionIdRoute
  ProjectsProjectIdFeaturesFeatureIdRoute: typeof ProjectsProjectIdFeaturesFeatureIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ws-session/$sessionId': {
      id: '/ws-session/$sessionId'
      path: '/ws-session/$sessionId'
      fullPath: '/ws-session/$sessionId'
      preLoaderRoute: typeof WsSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/features/$featureId': {
      id: '/projects/$projectId/features/$featureId'
      path: '/projects/$projectId/features/$featureId'
      fullPath: '/projects/$projectId/features/$featureId'
      preLoaderRoute: typeof ProjectsProjectIdFeaturesFeatureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  SchedulesRoute: SchedulesRoute,
  SettingsRoute: SettingsRoute,
  WsSessionSessionIdRoute: WsSessionSessionIdRoute,
  ProjectsProjectIdFeaturesFeatureIdRoute:
    ProjectsProjectIdFeaturesFeatureIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
