import { useMemo, useState } from "react";
import { useGetUsageStats } from "@/api/generated";
import { apiErrorMessage } from "@/lib/api-errors";
import { Skeleton } from "@/components/ui/skeleton";
import { SettingsSection } from "@/components/settings/SettingsSection";
import { SettingsCard } from "@/components/settings/SettingsCard";
import { SettingsSubsection } from "@/components/settings/SettingsSubsection";
import { WARNING_BANNER_CLASS } from "@/components/settings/SettingsWarningsBanner";
import { UsageSegmentedControl } from "@/components/settings/stats/UsageSegmentedControl";
import { UsageSummaryTiles } from "@/components/settings/stats/UsageSummaryTiles";
import {
  UsagePlotPlaceholder,
  UsagePlotSkeleton,
} from "@/components/settings/stats/UsagePlotPlaceholder";
import { UsageTimelineChart } from "@/components/settings/stats/UsageTimelineChart";
import { useUsageCharts } from "@/components/settings/stats/use-usage-charts";
import {
  resolveEndDay,
  USAGE_METRIC_UNIT,
  type UsageGrouping,
  type UsageMetric,
  type UsageScale,
} from "@/components/settings/stats/usage-stats-model";
import { UsageRecordingWarning } from "@/components/settings/stats/UsageRecordingWarning";
import { cn } from "@/lib/utils";

const RANGE_OPTIONS = [
  { value: "7", label: "7d", title: "Last 7 days" },
  { value: "30", label: "30d", title: "Last 30 days" },
  { value: "90", label: "90d", title: "Last 90 days" },
] as const;

const METRIC_OPTIONS = [
  { value: "total", label: "Total", title: "Input plus output tokens" },
  { value: "input", label: "Input", title: "Input tokens processed by the provider" },
  { value: "output", label: "Output", title: "Output tokens generated by the provider" },
] as const satisfies readonly { value: UsageMetric; label: string; title: string }[];

const GROUPING_OPTIONS = [
  { value: "provider", label: "Provider", title: "One series per provider" },
  { value: "model", label: "Model", title: "One series per provider and model" },
] as const satisfies readonly { value: UsageGrouping; label: string; title: string }[];

const SCALE_OPTIONS = [
  { value: "absolute", label: "Absolute", title: "Each day against the busiest day" },
  { value: "share", label: "Share", title: "Each day as its own mix, filled to the top" },
] as const satisfies readonly { value: UsageScale; label: string; title: string }[];

export function StatsSection(): React.JSX.Element {
  const [range, setRange] = useState<(typeof RANGE_OPTIONS)[number]["value"]>("30");
  const [metric, setMetric] = useState<UsageMetric>("total");
  const [grouping, setGrouping] = useState<UsageGrouping>("provider");
  const [scale, setScale] = useState<UsageScale>("absolute");

  const windowDays = Number(range);
  const { data, isLoading, error } = useGetUsageStats({ days: windowDays });
  const entries = useMemo(() => data?.entries ?? [], [data?.entries]);
  // The backend computes the window's last day from the same clock that stamped
  // the rows; deriving it here would drift across UTC midnight.
  const endDay = resolveEndDay(data?.end_day);
  const { chart, summary } = useUsageCharts({
    entries,
    windowDays,
    endDay,
    metric,
    grouping,
  });

  return (
    <SettingsSection
      id="stats"
      title="Usage stats"
      description="Provider-reported token usage is kept independently of your conversations. Archiving or deleting a conversation does not erase it."
    >
      <SettingsCard>
        <SettingsSubsection
          title="Overview"
          description="Captured from each provider's native usage events as your agents work."
        >
          {/* One row of options for the whole overview: the tiles and the chart
              below answer to the same range, measure, grouping and scale. */}
          <div className="mb-5 flex flex-wrap items-center gap-2">
            <UsageSegmentedControl
              value={range}
              options={RANGE_OPTIONS}
              onChange={setRange}
              ariaLabel="Time range"
            />
            <UsageSegmentedControl
              value={metric}
              options={METRIC_OPTIONS}
              onChange={setMetric}
              ariaLabel="Measure"
            />
            <UsageSegmentedControl
              value={grouping}
              options={GROUPING_OPTIONS}
              onChange={setGrouping}
              ariaLabel="Group by"
            />
            <UsageSegmentedControl
              value={scale}
              options={SCALE_OPTIONS}
              onChange={setScale}
              ariaLabel="Scale"
            />
          </div>
          {/* Outside `StatsBody` on purpose: a failed write is often the reason
              there is nothing to chart, so it must survive the empty state. */}
          {data?.recording_issue ? (
            <div className="mb-4">
              <UsageRecordingWarning issue={data.recording_issue} />
            </div>
          ) : null}
          <StatsBody
            windowDays={windowDays}
            isLoading={isLoading}
            error={error}
            hasUsage={summary.totalInputTokens + summary.totalOutputTokens > 0}
          >
            <div className="space-y-5">
              <UsageSummaryTiles summary={summary} />
              {/* There can be usage and still nothing to chart: output tokens
                  over a window of input-only rows. */}
              {chart.max > 0 ? (
                <UsageTimelineChart
                  data={chart}
                  density="comfortable"
                  scale={scale}
                  metricLabel={USAGE_METRIC_UNIT[metric]}
                />
              ) : (
                <UsagePlotPlaceholder
                  days={windowDays}
                  density="comfortable"
                  className="grid place-items-center rounded-lg border border-dashed border-border/60 px-6 text-center text-xs text-muted-foreground"
                >
                  No {USAGE_METRIC_UNIT[metric]} in this range yet.
                </UsagePlotPlaceholder>
              )}
            </div>
          </StatsBody>
        </SettingsSubsection>
      </SettingsCard>
    </SettingsSection>
  );
}

export function StatsBody({
  windowDays,
  isLoading,
  error,
  hasUsage,
  children,
}: {
  /** Sizes the loading placeholder like the chart of the selected range. */
  windowDays: number;
  isLoading: boolean;
  error: unknown;
  hasUsage: boolean;
  children: React.ReactNode;
}): React.JSX.Element {
  if (error && !hasUsage) {
    return (
      <p className="rounded-lg border border-[color-mix(in_oklab,var(--acc-red)_35%,transparent)] bg-[color-mix(in_oklab,var(--acc-red)_5%,var(--card))] px-3 py-2.5 text-xs text-foreground">
        Could not load usage stats. {apiErrorMessage(error, "Please try again.")}
      </p>
    );
  }
  if (isLoading && !hasUsage) {
    return (
      <div className="space-y-5" aria-busy="true" aria-label="Loading usage stats">
        <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">
          {Array.from({ length: 4 }, (_, index) => (
            <Skeleton key={index} className="h-[62px] rounded-lg" />
          ))}
        </div>
        <UsagePlotSkeleton days={windowDays} density="comfortable" />
      </div>
    );
  }
  if (!hasUsage) {
    return (
      <p className="rounded-lg border border-dashed border-border/60 px-3 py-6 text-center text-xs text-muted-foreground">
        No usage recorded yet. Send a prompt to an agent and it will show up here.
      </p>
    );
  }
  if (!error) return <>{children}</>;
  return (
    <div className="space-y-4">
      <p role="status" className={cn(WARNING_BANNER_CLASS, "text-xs text-foreground")}>
        Could not refresh usage stats. Showing the last loaded data.{" "}
        {apiErrorMessage(error, "Please try again.")}
      </p>
      {children}
    </div>
  );
}
