// Regenerates every desktop-brand asset from the Index Dots mark (root
// DESIGN.md "Brand identity"): the in-app logo SVGs, the PWA/favicon set under
// public/, and the Electron app icons under icons/.
//
// Ring geometry is single-sourced from the landing package so the desktop mark
// can never drift from the brand mark. Standard cut (dots r1.9, core r5.5) for
// ≥48px; favicon cut (r3 / r7) for small sizes.
//
// Root-level copies (favicon.ico, apple-touch-icon*.png) matter: browsers and
// iOS auto-probe them, and our SPA answers unknown paths with index.html which
// iOS treats as a broken icon. Homescreen tiles are opaque + flattened (iOS
// ignores apple-touch-icon PNGs with an alpha channel).
//
// Generated assets are committed; re-run only when the brand mark changes.
// Run from packages/desktop: `node scripts/generate-icons.mjs`
import { fileURLToPath } from "node:url";
import path from "node:path";
import { mkdir, writeFile } from "node:fs/promises";
import sharp from "sharp";
import { ringDots } from "../../landing/src/lib/logo-dots.mjs";
import { ico } from "../../landing/scripts/lib/ico.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ASSETS_DIR = path.resolve(__dirname, "../assets");
const PUBLIC_DIR = path.resolve(__dirname, "../public");
const ICONS_DIR = path.join(PUBLIC_DIR, "icons");
const APP_ICONS_DIR = path.resolve(__dirname, "../icons");

const GROUND = "#131416";
const INK = "#eff0f2";
const EMERALD = "#2db47d";
// Light-ground variant (in-app logo on light themes, adaptive favicon).
const INK_LIGHT = "#222429";
const EMERALD_DEEP = "#087653";

const STANDARD_CUT = { dotR: 1.9, coreR: 5.5 };
const FAVICON_CUT = { dotR: 3, coreR: 7 };

const GENERATED = "<!-- Generated by scripts/generate-icons.mjs — do not edit by hand. -->";

function dotCircles(dotR) {
  return ringDots()
    .map((d) => `<circle cx="${d.cx}" cy="${d.cy}" r="${dotR}"/>`)
    .join("");
}

/** Transparent 48-grid mark — the in-app logo asset. */
function markSvg({ dotR, coreR }, dots, core) {
  return `${GENERATED}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
  <g fill="${dots}">${dotCircles(dotR)}</g>
  <circle cx="24" cy="24" r="${coreR}" fill="${core}"/>
</svg>
`;
}

/** Full-bleed graphite tile — PWA / touch icons (rasterized opaque). */
function tileSvg({ dotR, coreR }, markScale = 1) {
  const g =
    markScale === 1 ? "" : ` transform="translate(24 24) scale(${markScale}) translate(-24 -24)"`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
  <rect width="48" height="48" fill="${GROUND}"/>
  <g${g}><g fill="${INK}">${dotCircles(dotR)}</g>
  <circle cx="24" cy="24" r="${coreR}" fill="${EMERALD}"/></g>
</svg>`;
}

/** macOS-template squircle tile (1024 grid, transparent corners) — the
 *  Electron app icon. Small cuts swap in the thicker favicon dots. */
function appIconSvg({ dotR, coreR }, markScale) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
  <rect x="100" y="100" width="824" height="824" rx="185" ry="185" fill="${GROUND}"/>
  <g transform="translate(512 512) scale(${markScale}) translate(-24 -24)">
    <g fill="${INK}">${dotCircles(dotR)}</g>
    <circle cx="24" cy="24" r="${coreR}" fill="${EMERALD}"/>
  </g>
</svg>`;
}

// Mark spans ~560px of the 824px tile — same optical density as the
// full-bleed brand icons (mark bbox ≈ 68% of its ground).
const APP_ICON_STANDARD = appIconSvg(STANDARD_CUT, 17);
const APP_ICON_SMALL = appIconSvg(FAVICON_CUT, 16);

const png = (svg, size) =>
  sharp(Buffer.from(svg), { density: 300 }).resize(size, size).png().toBuffer();

/** Opaque flattened raster for homescreen tiles (no alpha — iOS requirement). */
const opaquePng = (svg, size) =>
  sharp(Buffer.from(svg), { density: 300 })
    .resize(size, size)
    .flatten({ background: GROUND })
    .removeAlpha()
    .png()
    .toBuffer();

/** ICNS container with modern PNG-compressed entries. */
function icns(entries) {
  const chunks = entries.map(({ type, buf }) => {
    const header = Buffer.alloc(8);
    header.write(type, 0, 4, "ascii");
    header.writeUInt32BE(buf.length + header.length, 4);
    return Buffer.concat([header, buf]);
  });
  const totalLength = 8 + chunks.reduce((total, chunk) => total + chunk.length, 0);
  const header = Buffer.alloc(8);
  header.write("icns", 0, 4, "ascii");
  header.writeUInt32BE(totalLength, 4);
  return Buffer.concat([header, ...chunks]);
}

// ─── In-app logo assets ────────────────────────────────────────────────────
await writeFile(
  path.join(ASSETS_DIR, "cadencr-mark-dark.svg"),
  markSvg(STANDARD_CUT, INK, EMERALD),
);
await writeFile(
  path.join(ASSETS_DIR, "cadencr-mark-light.svg"),
  markSvg(STANDARD_CUT, INK_LIGHT, EMERALD_DEEP),
);
console.log("wrote assets/cadencr-mark-{dark,light}.svg");

// ─── PWA + favicon set (public/) ───────────────────────────────────────────
await mkdir(ICONS_DIR, { recursive: true });
const TILES = [
  { svg: tileSvg(STANDARD_CUT), size: 192, file: path.join(ICONS_DIR, "icon-192.png") },
  { svg: tileSvg(STANDARD_CUT), size: 512, file: path.join(ICONS_DIR, "icon-512.png") },
  // Maskable: mark shrunk inside the safe circle so squircle/circle crops keep it.
  {
    svg: tileSvg(STANDARD_CUT, 0.74),
    size: 512,
    file: path.join(ICONS_DIR, "icon-maskable-512.png"),
  },
  { svg: tileSvg(STANDARD_CUT), size: 180, file: path.join(PUBLIC_DIR, "apple-touch-icon.png") },
  {
    svg: tileSvg(STANDARD_CUT),
    size: 180,
    file: path.join(PUBLIC_DIR, "apple-touch-icon-precomposed.png"),
  },
];
for (const { svg, size, file } of TILES) {
  await writeFile(file, await opaquePng(svg, size));
  console.log(`wrote ${path.relative(PUBLIC_DIR, file)} (${size}x${size})`);
}

// Tab favicon: transparent, favicon cut, adapts dots/core to the tab bar's
// color scheme (ink on dark, graphite on light).
await writeFile(
  path.join(PUBLIC_DIR, "favicon.svg"),
  `${GENERATED}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
  <style>
    .dots { fill: ${INK_LIGHT}; } .core { fill: ${EMERALD_DEEP}; }
    @media (prefers-color-scheme: dark) {
      .dots { fill: ${INK}; } .core { fill: ${EMERALD}; }
    }
  </style>
  <g class="dots">${dotCircles(FAVICON_CUT.dotR)}</g>
  <circle class="core" cx="24" cy="24" r="${FAVICON_CUT.coreR}"/>
</svg>
`,
);
console.log("wrote favicon.svg");

const faviconEntries = await Promise.all(
  [16, 32, 48].map(async (size) => ({
    size,
    buf: await png(tileSvg(size <= 32 ? FAVICON_CUT : STANDARD_CUT), size),
  })),
);
await writeFile(path.join(PUBLIC_DIR, "favicon.ico"), ico(faviconEntries));
console.log("wrote favicon.ico");

// ─── Electron app icons (icons/) ───────────────────────────────────────────
// electron-builder consumes the PNG directory on Linux and selects the best
// size for each desktop/package target. Keep these cuts generated from the
// same source as the macOS and Windows containers so platform packaging can
// never reintroduce a retired brand mark.
for (const size of [16, 32, 48, 64, 128, 256, 512]) {
  const svg = size <= 32 ? APP_ICON_SMALL : APP_ICON_STANDARD;
  await writeFile(path.join(APP_ICONS_DIR, `${size}x${size}.png`), await png(svg, size));
  console.log(`wrote icons/${size}x${size}.png`);
}
await writeFile(path.join(APP_ICONS_DIR, "icon.png"), await png(APP_ICON_STANDARD, 512));
console.log("wrote icons/icon.png");

const icoEntries = await Promise.all(
  [16, 32, 48, 256].map(async (size) => ({
    size,
    buf: await png(size <= 48 ? APP_ICON_SMALL : APP_ICON_STANDARD, size),
  })),
);
await writeFile(path.join(APP_ICONS_DIR, "icon.ico"), ico(icoEntries));
console.log("wrote icons/icon.ico");

// macOS ICNS. Retina pairs intentionally repeat physical sizes under their
// scale-aware chunk identifiers; small sizes use the thicker favicon cut.
const ICNS = [
  ["ic04", 16],
  ["ic11", 32],
  ["ic05", 32],
  ["ic12", 64],
  ["ic07", 128],
  ["ic13", 256],
  ["ic08", 256],
  ["ic14", 512],
  ["ic09", 512],
  ["ic10", 1024],
];
const icnsEntries = await Promise.all(
  ICNS.map(async ([type, size]) => ({
    type,
    buf: await png(size <= 32 ? APP_ICON_SMALL : APP_ICON_STANDARD, size),
  })),
);
await writeFile(path.join(APP_ICONS_DIR, "icon.icns"), icns(icnsEntries));
console.log("wrote icons/icon.icns");
